networks:
  blog-network:

services:
  blog-db:
    image: mysql:8.0
    container_name: blog-db
    environment:
      MYSQL_ROOT_PASSWORD: SuperSecretPassword@1234
      MYSQL_DATABASE: blog
      MYSQL_USER: user
      MYSQL_PASSWORD: SuperSecretPassword@1234
    ports:
      - "3309:3306"
    volumes:
      - blog-data:/var/lib/mysql
    networks:
      - blog-network

  blog-be:
    image: blog-be
    container_name: blog-be
    build:
      dockerfile: Dockerfile
      context: ./blog-be
    environment:
      SPRING_APPLICATION_NAME: blog-be
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:mysql://blog-db:3306/blog?serverTimezone=UTC&useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: SuperSecretPassword@1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      APPLICATION_SECURITY_JWT_SECRET_KEY: ECPCVSx5bhnlEWVnESptXEyOPI9KeGUUECPCVSx5bhnlEWVnESptXEyOPI9KeGUU
    ports:
      - "8081:8080"
    networks:
      - blog-network
    depends_on:
      - blog-db

  blog-web-app:
    image: blog-web-app
    container_name: blog-web-app
    build:
      context: ./blog-web-app
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    depends_on:
      - blog-be
    networks:
      - blog-network

volumes:
  blog-data:
